Messages:
  Death_Message: "&cOuch! Hit the ground too hard? Click here to return to your death location!"
  Teleport_Deny_Message: "&cSorry! You can only return to this location once!"
  Teleport_Success_Message: "&2Teleported you back!"


Version: 1