name: ${project.name}
version: ${project.version}
main: ${main.class}
api-version: 1.15
author: Ares

commands:
  test:
    description: "Fancy plugin"
    aliases: [test]
#permissions:
#  teleport.on.death:
#    default: op